load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")
load("//:lints/cargo_lint_sources.bzl", "cargo_lint_sources")

package(default_visibility = ["//visibility:public"])

cargo_lint_sources()

exports_files(["Cargo.toml"])

rust_library(
    name = "honk-grpc",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/bin/**"],
    ),
    aliases = aliases(),
    crate_name = "honk_grpc",
    edition = "2021",
    deps = [
        "//crates/honk:honk_lib",
        "//crates/honk-grpc-proto:honk-grpc-proto",
    ] + all_crate_deps(),
)

rust_binary(
    name = "honkd",
    srcs = ["src/bin/honkd.rs"],
    aliases = aliases(),
    crate_name = "honkd",
    crate_root = "src/bin/honkd.rs",
    edition = "2021",
    deps = [
        ":honk-grpc",
        "//crates/honk:honk_lib",
    ] + all_crate_deps(),
)

rust_test(
    name = "honk_grpc_unit_tests",
    size = "small",
    timeout = "short",
    crate = ":honk-grpc",
)
