[package]
name = "nockchain-libp2p-io"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]

async-trait = { workspace = true }
bs58 = { workspace = true }
bytes = { workspace = true }
config = { workspace = true }
dashmap = { workspace = true }
either = { workspace = true }
equix.workspace = true
futures = { workspace = true }
gnort = { workspace = true }
hickory-proto = { workspace = true }
hickory-resolver = { workspace = true }
ibig = { workspace = true }
libp2p = { workspace = true, features = [
  "ping",
  "kad",
  "identify",
  "quic",
  "tls",
  "dns",
  "tokio",
  "macros",
  "request-response",
  "memory-connection-limits",
  "peer-store",
] }
nockapp = { workspace = true }
nockchain-math = { workspace = true }
nockvm = { workspace = true }
nockvm_macros = { workspace = true }
noun-serde = { workspace = true }
num-bigint.workspace = true
prost = { workspace = true }
rand = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["alloc", "derive", "serde_derive"] }
serde_bytes = { workspace = true, features = ["alloc"] }
signal-hook = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
prost-types = { workspace = true }

[dev-dependencies]
cbor4ii = { workspace = true, features = ["serde1", "use_std"] }
chaff = { workspace = true }
hex = { workspace = true }
kernels-open-dumb = { workspace = true }
nockapp-grpc-proto = { workspace = true }
nockchain = { workspace = true }
nockchain-types = { workspace = true }
prost-types = { workspace = true }
quickcheck = { workspace = true }
serde_cbor = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
tonic = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
zkvm-jetpack = { workspace = true }

[lints]
workspace = true
