# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import inference_mining_pb2 as inference__mining__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_mining_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceMiningServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterRuntime = channel.unary_unary(
                '/nockchain.ai_pow.v1.InferenceMiningService/RegisterRuntime',
                request_serializer=inference__mining__pb2.RegisterRuntimeRequest.SerializeToString,
                response_deserializer=inference__mining__pb2.RegisterRuntimeResponse.FromString,
                _registered_method=True)
        self.HeartbeatRuntime = channel.unary_unary(
                '/nockchain.ai_pow.v1.InferenceMiningService/HeartbeatRuntime',
                request_serializer=inference__mining__pb2.HeartbeatRuntimeRequest.SerializeToString,
                response_deserializer=inference__mining__pb2.HeartbeatRuntimeResponse.FromString,
                _registered_method=True)
        self.GetMiningJob = channel.unary_unary(
                '/nockchain.ai_pow.v1.InferenceMiningService/GetMiningJob',
                request_serializer=inference__mining__pb2.GetMiningJobRequest.SerializeToString,
                response_deserializer=inference__mining__pb2.MiningJob.FromString,
                _registered_method=True)
        self.NotifyWork = channel.unary_unary(
                '/nockchain.ai_pow.v1.InferenceMiningService/NotifyWork',
                request_serializer=inference__mining__pb2.NotifyWorkRequest.SerializeToString,
                response_deserializer=inference__mining__pb2.NotifyWorkResponse.FromString,
                _registered_method=True)
        self.SubmitOpenedBlock = channel.stream_unary(
                '/nockchain.ai_pow.v1.InferenceMiningService/SubmitOpenedBlock',
                request_serializer=inference__mining__pb2.OpenedBlockPart.SerializeToString,
                response_deserializer=inference__mining__pb2.SubmitOpenedBlockResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/nockchain.ai_pow.v1.InferenceMiningService/GetStatus',
                request_serializer=inference__mining__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=inference__mining__pb2.InferenceMiningStatus.FromString,
                _registered_method=True)


class InferenceMiningServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeartbeatRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMiningJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyWork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitOpenedBlock(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceMiningServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterRuntime,
                    request_deserializer=inference__mining__pb2.RegisterRuntimeRequest.FromString,
                    response_serializer=inference__mining__pb2.RegisterRuntimeResponse.SerializeToString,
            ),
            'HeartbeatRuntime': grpc.unary_unary_rpc_method_handler(
                    servicer.HeartbeatRuntime,
                    request_deserializer=inference__mining__pb2.HeartbeatRuntimeRequest.FromString,
                    response_serializer=inference__mining__pb2.HeartbeatRuntimeResponse.SerializeToString,
            ),
            'GetMiningJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMiningJob,
                    request_deserializer=inference__mining__pb2.GetMiningJobRequest.FromString,
                    response_serializer=inference__mining__pb2.MiningJob.SerializeToString,
            ),
            'NotifyWork': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyWork,
                    request_deserializer=inference__mining__pb2.NotifyWorkRequest.FromString,
                    response_serializer=inference__mining__pb2.NotifyWorkResponse.SerializeToString,
            ),
            'SubmitOpenedBlock': grpc.stream_unary_rpc_method_handler(
                    servicer.SubmitOpenedBlock,
                    request_deserializer=inference__mining__pb2.OpenedBlockPart.FromString,
                    response_serializer=inference__mining__pb2.SubmitOpenedBlockResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=inference__mining__pb2.GetStatusRequest.FromString,
                    response_serializer=inference__mining__pb2.InferenceMiningStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nockchain.ai_pow.v1.InferenceMiningService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nockchain.ai_pow.v1.InferenceMiningService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceMiningService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nockchain.ai_pow.v1.InferenceMiningService/RegisterRuntime',
            inference__mining__pb2.RegisterRuntimeRequest.SerializeToString,
            inference__mining__pb2.RegisterRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeartbeatRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nockchain.ai_pow.v1.InferenceMiningService/HeartbeatRuntime',
            inference__mining__pb2.HeartbeatRuntimeRequest.SerializeToString,
            inference__mining__pb2.HeartbeatRuntimeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMiningJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nockchain.ai_pow.v1.InferenceMiningService/GetMiningJob',
            inference__mining__pb2.GetMiningJobRequest.SerializeToString,
            inference__mining__pb2.MiningJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyWork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nockchain.ai_pow.v1.InferenceMiningService/NotifyWork',
            inference__mining__pb2.NotifyWorkRequest.SerializeToString,
            inference__mining__pb2.NotifyWorkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitOpenedBlock(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/nockchain.ai_pow.v1.InferenceMiningService/SubmitOpenedBlock',
            inference__mining__pb2.OpenedBlockPart.SerializeToString,
            inference__mining__pb2.SubmitOpenedBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nockchain.ai_pow.v1.InferenceMiningService/GetStatus',
            inference__mining__pb2.GetStatusRequest.SerializeToString,
            inference__mining__pb2.InferenceMiningStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
