[package]
name = "bridge-dev"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
alloy = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
bridge = { path = "../bridge" }
bs58 = { workspace = true }
clap = { workspace = true, features = ["derive"] }
flate2 = { workspace = true }
hex = { workspace = true }
ibig = { workspace = true }
libc = { workspace = true }
nockapp-grpc = { workspace = true }
nockchain-math = { workspace = true }
nockchain-types = { path = "../nockchain-types" }
op-alloy = { workspace = true, features = ["network"] }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = [
    "fs",
    "io-util",
    "macros",
    "net",
    "process",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
toml = { workspace = true }
tonic = { workspace = true }

[dev-dependencies]
aws-sdk-s3 = { workspace = true }
proptest = { workspace = true }

[lints]
workspace = true
